export const GET_MARKERS_SUCCESS = "GET_MARKERS_SUCCESS";
export const SET_CURRENT_MARKER = "SET_CURRENT_MARKER";
export const GET_MARKERINFO_SUCCESS = "GET_MARKERINFO_SUCCESS";
export const SET_NEIGHBOURHOODS = "SET_NEIGHBOURHOODS";
export const SET_FILTERED_MARKERS = "SET_FILTERED_MARKERS";